### ISSUE TITLE
anitya doesn't run checks for new versions

### ISSUE THREAD

**Issue by ignatenkobrain** [release-monitoring/anitya#605] opened 2018-09-10 18:08 UTC
We've noticed that we don't get notifications for new versions for projects with `crates.io` backend. They just doesn't seem to be checked.

Manual refresh does the trick.

**Comment by Heidistein** [comment] 2018-09-12 06:56
I have noticed this indied on multiple projects. Django, apache httpd, libzip (was broken, and some more.
Today I noticed it with PHP

**Comment by Zlopez** [comment] 2018-09-12 07:31
I will look into it.

**Comment by Zlopez** [comment] 2018-09-12 14:59
According to the cron job log we got an unhandled exception:
```
Unhandled exception in thread started by <bound method
DummyProcess.__bootstrap of <DummyProcess(Thread-7, stopped daemon
140222260033280)>>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 785, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 825, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib64/python2.7/traceback.py", line 240, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
```

I will try to find a root of it, but in the first glance it looks like something is missing when creating process.

**Comment by Zlopez** [comment] 2018-09-17 07:11
@srakitnican 
This is probably caused by the failing cron job.

**Comment by Zlopez** [comment] 2018-09-18 10:44
It looks like the current version deployed on staging doesn't have this issue.
So after moving this to production, this should be solved.

**Comment by Zlopez** [comment] 2018-09-20 10:10
When I tried to run cron job locally, I got `UnicodeEncodeError` caused by this project https://release-monitoring.org/project/16189/

It looks like I found the root of this issue.

I'm working on the fix now.

**Comment by Zlopez** [comment] 2018-09-24 15:08
Should be fixed in 0.13.1

**Closed by Zlopez** 2018-09-24 15:08 UTC
Labels: bug
