### ISSUE TITLE
New version of nextcloud-client not detected

### ISSUE THREAD

**Issue by janvlug** [release-monitoring/anitya#676] opened 2018-12-08 12:03 UTC
The new [2.5.1 version](https://github.com/nextcloud/desktop/releases/tag/v2.5.1) of nextcloud-client is not visible on this page:
https://release-monitoring.org/project/18381/

**Comment by Zlopez** [comment] 2018-12-10 08:20
This is probably caused by the ratelimit for github. I'm working on the fix right now and it should part of 0.14.0 release.

**Comment by cheese1** [comment] 2019-01-04 18:23
probably because release-monitoring.org does not check:

Last check started at (UTC) 2018-12-04 00:10:11 (at the bottom of each page)

#663 
#683 
#684

**Comment by Zlopez** [comment] 2019-01-10 15:55
This is fixed now. Checking is working again and the version 2.5.1 is retrieved. Closing.

**Closed by Zlopez** 2019-01-10 15:55 UTC
Labels: bug
