### ISSUE TITLE
xsane release monitoring is following bad project

### ISSUE THREAD

**Issue by zdohnal** [release-monitoring/anitya#810] opened 2019-08-20 08:16 UTC
Hi,

I got the report from release monitoring https://bugzilla.redhat.com/show_bug.cgi?id=1742431 about new release of xsane, but when I go to their pages, there is no new release https://gitlab.com/sane-project/frontend/xsane/-/releases .

It seems release monitoring started to follow sane-frontends project, even when URL and homepage are set to correct xsane github.

Would anyone mind looking into it?

**Comment by Zlopez** [comment] 2019-08-20 08:44
xsane is one of the project, that is hitting this issue https://github.com/release-monitoring/anitya/issues/763
But somebody must have changed it recently and then reset the changes, this is why it found the new version.

**Comment by Zlopez** [comment] 2019-09-06 12:38
Closing as a duplicate of #763

**Closed by Zlopez** 2019-09-06 12:38 UTC
Labels: bug
