### ISSUE TITLE
Package updates missing in datagrepper

### ISSUE THREAD

**Issue by mnhauke** [release-monitoring/anitya#638] opened 2018-10-16 20:06 UTC
Since some weeks datagrepper does not get all anitya project version update messages (topic=org.release-monitoring.prod.anitya.project.version.update).

Especially updates from packages with the _GitHub backend_ seems to be affected.

Examples:
* sdrangel
  * https://release-monitoring.org/project/14479/
    * https://github.com/f4exb/sdrangel/releases
    * latest upstream release 2 days ago (14.10.2018)
* srslte
  * https://release-monitoring.org/project/16192/
    * https://github.com/srsLTE/srsLTE/releases
    * latest upstream release 1 days ago (15.10.2018)

You can see that both projects were properly updated on release-monitoring.org but I can't find those updates in the datagrepper database.

I have attached a python scripts that shows all version updates from a given timeframe.
As you can see in the script there are only very few updates for projects with the GitHub backend.

[relmon.py](https://github.com/release-monitoring/anitya/files/2484726/relmon.txt)

[relmon-last4-weeks.txt](https://github.com/release-monitoring/anitya/files/2484721/relmon-last4-weeks.txt)

**Comment by Zlopez** [comment] 2018-10-17 07:36
@jeremycline 
Is there anything we can do? This looks like fedmsg is losing messages. Github doesn't have any special exception when checking for new version. It should work like any other backend.

After release of version 0.13.1, there was plenty of projects (thousands), that were updated at once, maybe this is the reason.

**Comment by Zlopez** [comment] 2018-10-17 11:34
@nqb 
No, this is the same issue. Fedora notifications is using fedmsg so the flow is same as in case of datagrepper.

**Comment by nqb** [comment] 2018-10-17 11:47
Thanks a lot @Zlopez, tell me if I can provide some useful informations.

On my side, I notice this unexpected behavior with [Kanboard project](https://release-monitoring.org/project/12299/), release 1.2.6.

**Comment by voxik** [comment] 2018-10-18 10:30
I don't see new BZ reported in Fedora, is it the same issue? Neither I get notifications from FMN.

**Comment by Zlopez** [comment] 2018-10-18 11:00
@voxik 
This is the same issue.

I created a [ticket](https://pagure.io/fedora-infrastructure/issue/7313) in Fedora infra, hopefully this will be solved soon.

**Comment by nqb** [comment] 2018-10-20 12:46
@Zlopez, 

issue seems to be fixed with the release of Anitya 0.13.2, I receive notifications messages about anitya project.

**Comment by Zlopez** [comment] 2018-10-22 08:36
@nqb 
Not sure if this is fixed, there wasn't any change in the notifications in this version.
Maybe the issue was somewhere else in the chain.
I will left this open for now.

**Comment by nqb** [comment] 2018-11-08 10:45
@Zlopez 

Issue still presents. For PacketFence project, I didn't receive notifications for 8.2 released yesterday.

**Comment by Zlopez** [comment] 2018-11-08 11:16
I know, we are now working to move Anitya from fedmsg to fedora-messaging. This should prevent this issue in future.

**Comment by Zlopez** [comment] 2019-01-18 14:10
I finally found the issue and fixed this. The messages are now sent to datagrepper correctly:
https://apps.fedoraproject.org/datagrepper/raw?category=anitya&delta=604800

I'm closing this issue now.
For anyone interested the issue was only in cron job that was missing USER env variable.

**Closed by Zlopez** 2019-01-18 14:10 UTC
Labels: fedmsg
