### ISSUE TITLE
Distinguish stable / devel releases ?

### ISSUE THREAD

**Issue by tpetazzoni** [release-monitoring/anitya#792] opened 2019-06-20 12:58 UTC
The Buildroot project is using release-monitoring.org to make sure we have the latest version of the different software components packaged in Buildroot. Of course as a distribution/build system, Buildroot only packages "stable" versions of software components.

However, some upstream projects such as many of the Gnome project like to make some development releases. This is the case for ATK for example: https://release-monitoring.org/project/130/. The release that have a odd number (2.31.x, 2.33.x, etc.) are development releases, while the stable releases have a even number.

So right now, when we compare the version in Buildroot with the latest version reported by release-monitoring.org, they differ because release-monitoring.org reports 2.33.3 as being the latest.

Would it be possible to have a mechanism to distinguish stable vs. development versions ? Or perhaps release-monitoring.org should have a way of filtering versions and only report stable ones ?

**Comment by tpetazzoni** [comment] 2019-06-20 13:00
A similar problem occurs with znc: its release candidates are considered newer than the latest stable version: https://release-monitoring.org/project/5305/

**Comment by Zlopez** [comment] 2019-06-20 13:05
This looks similar to https://github.com/release-monitoring/anitya/issues/753

**Comment by tpetazzoni** [comment] 2019-06-20 13:09
Indeed, it is exactly the same "bug". Is there are way to mark this one as a duplicate ? Or should we simply close this issue ? Thanks for the feedback!

**Comment by Zlopez** [comment] 2019-06-20 13:11
Closed as duplicate of #753

**Closed by Zlopez** 2019-06-20 13:11 UTC
Labels: enhancement
