### ISSUE TITLE
Changing project backend doesn't update project ecosystem

### ISSUE THREAD

**Issue by ncoghlan** [release-monitoring/anitya#400] opened 2017-01-11 12:12 UTC
Trying to use the `by_ecosystem` query API with release-monitoring.org today, I realised it has a couple of problems:

1. The "ecosystem" field only gets populated when a project gets created, so all the pre-existing projects don't have it, and hence can't be found via the `by_ecosystem` query API
2. When a project is edited to change the backend, the nominal ecosystem isn't updated accordingly

I'd missed this when submitting the change as I'd only previously used the feature on an Anitya installation that started from scratch with the ecosystem changes applied.

**Comment by jeremycline** [comment] 2017-02-20 11:45
1. should be fixed, but I believe 2. is still an outstanding issue.

**Comment by ncoghlan** [comment] 2017-03-16 03:21
I updated the issue title to match the remaining problem, as changing the nominal ecosystem affects more than just the by_ecosystem API - it affects the uniqueness constraints imposed by the database.

Perhaps it's time to expose Ecosystems in the UI and documentation as a distinct concept from the update monitoring backend?

**Comment by Zlopez** [comment] 2018-10-08 08:00
The https://github.com/release-monitoring/anitya/pull/625 added ecosystem information to GUI.

I will update the documentation to contain this information and will check if the issue is still there on edit.

**Comment by Zlopez** [comment] 2020-01-09 12:24
This was implemented in #859

**Closed by Zlopez** 2020-01-09 12:24 UTC
Labels: bug
