### ISSUE TITLE
Cannot add a new distro in a separate Anitya instance

### ISSUE THREAD

**Issue by dfateyev** [release-monitoring/anitya#802] opened 2019-08-09 11:46 UTC
Error while trying to add a new distro:
```
[wsgi:error] [pid 10479] [anitya.app ERROR] Exception on /distro/add [POST]
[wsgi:error] [pid 10479] Traceback (most recent call last):
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/flask/app.py", line 2446, in wsgi_app
[wsgi:error] [pid 10479]     response = self.full_dispatch_request()
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/flask/app.py", line 1951, in full_dispatch_request
[wsgi:error] [pid 10479]     rv = self.handle_user_exception(e)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 269, in error_router
[wsgi:error] [pid 10479]     return original_handler(e)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/flask/app.py", line 1820, in handle_user_exception
[wsgi:error] [pid 10479]     reraise(exc_type, exc_value, tb)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/flask/_compat.py", line 39, in reraise
[wsgi:error] [pid 10479]     raise value
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/flask/app.py", line 1949, in full_dispatch_request
[wsgi:error] [pid 10479]     rv = self.dispatch_request()
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/flask/app.py", line 1935, in dispatch_request
[wsgi:error] [pid 10479]     return self.view_functions[rule.endpoint](**req.view_args)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/flask_login/utils.py", line 261, in decorated_view
[wsgi:error] [pid 10479]     return func(*args, **kwargs)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/anitya/ui.py", line 324, in add_distro
[wsgi:error] [pid 10479]     message=dict(agent=flask.g.user.username, distro=distro.name),
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/anitya/lib/utilities.py", line 231, in log
[wsgi:error] [pid 10479]     topic=topic, msg=dict(project=project, distro=distro, message=message)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/anitya/lib/utilities.py", line 63, in fedmsg_publish
[wsgi:error] [pid 10479]     topic="anitya.{}".format(kwargs["topic"]), body=kwargs["msg"]
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/fedora_messaging/api.py", line 246, in publish
[wsgi:error] [pid 10479]     _session_cache.session.publish(message, exchange=exchange)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/fedora_messaging/_session.py", line 152, in publish
[wsgi:error] [pid 10479]     self._connect_and_publish(exchange, message)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/fedora_messaging/_session.py", line 193, in _connect_and_publish
[wsgi:error] [pid 10479]     body=message._encoded_body,
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/fedora_messaging/message.py", line 499, in _encoded_body
[wsgi:error] [pid 10479]     return json.dumps(self.body).encode("utf-8")
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib64/python3.4/json/__init__.py", line 230, in dumps
[wsgi:error] [pid 10479]     return _default_encoder.encode(obj)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib64/python3.4/json/encoder.py", line 192, in encode
[wsgi:error] [pid 10479]     chunks = self.iterencode(o, _one_shot=True)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib64/python3.4/json/encoder.py", line 250, in iterencode
[wsgi:error] [pid 10479]     return _iterencode(o, 0)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib64/python3.4/json/encoder.py", line 173, in default
[wsgi:error] [pid 10479]     raise TypeError(repr(o) + " is not JSON serializable")
[wsgi:error] [pid 10479] TypeError: <anitya.db.models.Distro object at 0x7efe3df5aeb8> is not JSON serializable
```
Using python-3.4.2 with WSGI, the DB type is SQLite.
Tried various values as "distro" name, but haven't got any luck with the same error, maybe related to #791 or #800.

**Comment by Zlopez** [comment] 2019-08-09 19:41
Thanks, but this is the duplicate of #791 and there is a PR that is fixing this issue.

**Closed by Zlopez** 2019-08-09 19:42 UTC
