### ISSUE TITLE
RFE: support GitHub hook notifications

### ISSUE THREAD

**Issue by ktdreyer** [release-monitoring/anitya#494] opened 2017-06-06 16:28 UTC
I've been thinking through how to get immediate notifications when we tag Ceph projects upstream. I'd like to use https://release-monitoring.org/ , but the cron polling model is a bit too slow to use for CI and event-driven workflows.

Can I configure my GitHub projects' webhooks to hit some API on https://release-monitoring.org/ every time I push a new Git tag?

**Comment by jeremycline** [comment] 2017-06-06 17:12
I'm afraid that API isn't currently available, but it's definitely something I'd like for Anitya to have and others have asked for it (this is a duplicate of #328) - it's mostly about finding the time to get it done. Another thing I started on (and need to tidy up in the near future) is integration with libraries.io (https://github.com/release-monitoring/anitya/issues/403) which should help with the significant lag introduced by the current polling model.

I really hope to find the time in the near future to get this (and a lot of other stuff Anitya needs) done.

**Closed by jeremycline** 2017-06-06 17:12 UTC
