### ISSUE TITLE
RFE: option to delete all *old* matches, after updating the regex

### ISSUE THREAD

**Issue by cheese1** [release-monitoring/anitya#879] opened 2020-01-07 09:58 UTC
sometimes one has to update the regex, because the target website changes.
would be great, if one could delete *old* matches and start fresh. there could be alot wrong entries, which would need to be be removed (currently manual job).

**Comment by Zlopez** [comment] 2020-01-07 10:32
Possible duplicate of https://github.com/release-monitoring/anitya/issues/623
This could be also solved by https://github.com/release-monitoring/anitya/issues/491

**Closed by Zlopez** 2020-01-07 10:32 UTC
