### ISSUE TITLE
Visiting distro pages throws HTTP 500 errors

### ISSUE THREAD

**Issue by Conan-Kudo** [release-monitoring/anitya#756] opened 2019-03-26 10:58 UTC
When visiting release-monitoring.org and trying to visit any distro page, the site throws an HTTP 500 error.

E.g.: https://release-monitoring.org/distro/Fedora/

**Comment by Conan-Kudo** [comment] 2019-03-26 10:58
This was also noticed by @fedya: https://github.com/OpenMandrivaSoftware/rosa-build/issues/28#issuecomment-475990145

**Comment by Zlopez** [comment] 2019-03-26 12:25
Duplicate of https://github.com/release-monitoring/anitya/issues/709

**Closed by Zlopez** 2019-03-26 12:25 UTC
