### ISSUE TITLE
New version of Solr not detected

### ISSUE THREAD

**Issue by Heidistein** [release-monitoring/anitya#683] opened 2018-12-17 14:40 UTC
In project solr [1] the latest version is not detect, which was released about five days ago...

https://release-monitoring.org/project/17398/

**Comment by Zlopez** [comment] 2018-12-17 15:07
This is probably caused by crash happening in cron script, which is checking for new releases. This should be fixed by https://github.com/release-monitoring/anitya/pull/663
I hope to release this fix in 0.14.0 release.

**Comment by cheese1** [comment] 2018-12-30 21:15
we should create a faster fix. if one uses release-monitoring.org than this could be a big problem, if new versions wont get correctly and timely checked. what if security-problems where fixed?

**Comment by Zlopez** [comment] 2018-12-30 23:07
I know this is a annoying situation, but I hope I will be able to release the new version soon.
I just need to merge three more PRs before release of new version (#678, #669, #635). The third one is not critical, but it will be nice.

**Comment by Zlopez** [comment] 2019-01-10 15:48
Checked the https://stg.release-monitoring.org/project/17398/ and the version is retrieved. Closing this issue as solved.

**Closed by Zlopez** 2019-01-10 15:48 UTC
Labels: bug
