### ISSUE TITLE
Wrong version fetched from GitHub.

### ISSUE THREAD

**Issue by layus** [release-monitoring/anitya#660] opened 2018-11-18 08:53 UTC
For buck (facebook build system), the oldest version is detected, instead of the most recent one.

See https://release-monitoring.org/project/18388/ where version is 2015.09.10.01 while it should be 2018.10.29.01 as per https://github.com/facebook/buck/releases.

I have not had time to debug this.

**Comment by Zlopez** [comment] 2018-11-18 10:36
Duplicate of https://github.com/release-monitoring/anitya/issues/642

**Closed by Zlopez** 2018-11-18 10:36 UTC

**Comment by layus** [comment] 2018-11-18 14:00
Oops, sorry for the duplicate. And thanks for the patch in master :-)
