### ISSUE TITLE
version prefix not working as expected

### ISSUE THREAD

**Issue by glensc** [release-monitoring/anitya#241] opened 2015-12-14 21:07 UTC
So, i created project Smarty2:
https://release-monitoring.org/project/8379/
and filled Version Prefix as "v2.6"

i expected it to find only releases staring with that prefix, but instead it found "v3.1.28"

please add documentation, what the "Version prefix" does and what for it's to be used.

**Comment by pypingou** [comment] 2015-12-14 22:23
The prefix is a character or more to be removed when the version if found. So that for example ``v1.2`` becomes ``1.2`` or ``foo-2.4`` becomes ``2.4``. Making versions comparison easier

**Comment by hobbes1069** [comment] 2016-02-18 19:46
How would one go about limiting the results to filter out bad results then? I'm trying to do something similar with OCE but they have both their tags "OCE-0.17.1" and the sources their forked from "official/6.8.0". It's picking up the latter when I need it to pick up the first one.

**Comment by pypingou** [comment] 2016-02-18 21:19
You could use a custom regex to pick only the ``OCE-`` ones

**Comment by pypingou** [comment] 2016-06-17 08:13
I feel like this ticket is already fixed in https://release-monitoring.org/about

Thoughts?

**Comment by mattdm** [comment] 2017-08-18 23:35
It'd be super-awesome to have this documented on the "edit project" page. I was confused, and this issue is where google lead me to figure things out. Which worked, but probably is not optimal. :)

**Comment by jeremycline** [comment] 2018-08-11 14:31
This is actually a duplicate of https://github.com/release-monitoring/anitya/issues/184, so we're just going to track that there

**Closed by jeremycline** 2018-08-11 14:31 UTC
Labels: docs, easyfix
