### ISSUE TITLE
release-monitoring.org not checking for updates?

### ISSUE THREAD

**Issue by cheese1** [release-monitoring/anitya#684] opened 2018-12-30 20:46 UTC
sysdig 0.24.2 was not found until manually triggered check (via editing the definitions and clicking on "check altest release on submit)

the page (release-monitoring.org) reads:
...
Anitya (0.13.2): API -- sources -- issue tracker . ©2013-2016 Red Hat, Inc., pingou. Last check started at (UTC) 2018-12-04 00:10:11 

"2018-12-04" seems to be a bit old

**Comment by Zlopez** [comment] 2018-12-30 23:17
This is caused by failing cron job, but this is already fixed in #663, but not merged yet
If you want to do a review, you are welcome

**Comment by cheese1** [comment] 2019-01-05 17:08
sorry, not enough knowledge with python.
i mailed on fedora-packagers, maybe someone will be able to do that

**Comment by cheese1** [comment] 2019-01-06 17:16
sorry, not enough knowledge with python.
i mailed on fedora-packagers, maybe someone will be able to do that

**Comment by abitrolly** [comment] 2019-01-07 09:35
Is it possible to expose queue status?

**Comment by Zlopez** [comment] 2019-01-07 09:53
@abitrolly What queue do you mean?

**Comment by abitrolly** [comment] 2019-01-07 09:55
Projects check queue. If it it running. I landed here, because I had to update `meld` manually.

**Comment by Zlopez** [comment] 2019-01-07 10:04
It's not running at all, the cron job fails on start with error above. It looks like there was some automatic rebuild on 4th December and the behavior of setup or import handling was changed in python. I will try to fix this on release-monitoring.org, probably by creating symlink to cron script. I will also try to fix this in anitya as longterm solution. Probably by implementing #668.

**Comment by abitrolly** [comment] 2019-01-07 11:09
@Zlopez the status check in case of cron job is a heartbeat (time since last time it was active), last return code and counter of errors for the last hour.

**Comment by Zlopez** [comment] 2019-01-07 11:45
@abitrolly There is nothing like this, it's simple cron job that is run by OpenShift every 12 hours. After conversion to service, it will be handled as separate container.

**Comment by abitrolly** [comment] 2019-01-07 11:58
And what would be the way to monitor the status of this container and show it in the footer?

**Comment by Zlopez** [comment] 2019-01-07 12:01
I will probably implement some kind of heartbeat for this.

**Comment by Zlopez** [comment] 2019-01-07 12:15
The fix is now live on release-monitoring.org
There are still issues with cron job (I hope most of them will be fixed by release 0.14.0), but at least it's running again now.
Closing this issue.

**Closed by Zlopez** 2019-01-07 12:15 UTC
Labels: release-monitoring.org

**Comment by cheese1** [comment] 2019-01-07 12:19
Thanks

**Comment by abitrolly** [comment] 2019-01-07 12:21
There are some easy [queues](http://python-rq.org/) for Python. Haven't found if they support queue status checks.

**Comment by abitrolly** [comment] 2019-01-07 18:34
@Zlopez Twisted doesn't store state between processes and between servers. It won't solve the problem, because it is just an async framework. Job queues written with Twisted still use that - http://queues.io/#restmq and https://github.com/calston/rhumba 

I am not a fan of Twisted because of code complexity. You may want to read https://www.transceptor.technology/single-post/2016/08/19/Part-1-Avoiding-callback-hell-in-Python first.
