### ISSUE TITLE
GitHub backend fails fetching tags on some projects

### ISSUE THREAD

**Issue by akien-mga** [release-monitoring/anitya#624] opened 2018-10-01 21:58 UTC
This appears to be a regression as it used to work, but no longer does.

See the project [goxel](https://release-monitoring.org/project/12163/) on release-monitoring. It reports an error when trying to get the latest version:
```
Unable to retrieve the latest version from upstream!
ERROR: goxel: no upstream version found. - https://github.com/guillaumechereau/goxel/tags -  class="tag-name">([^<]*)</span
```
Yet [the URL is valid](https://github.com/guillaumechereau/goxel/tags) and the tags have a format that Anitya should be able to parse.

**Comment by Zlopez** [comment] 2018-10-02 08:17
Duplicate of https://github.com/release-monitoring/anitya/issues/581

**Closed by Zlopez** 2018-10-02 08:17 UTC
