### ISSUE TITLE
Anitya home website - distro list returning 500 error.

### ISSUE THREAD

**Issue by mattmarillac** [release-monitoring/anitya#794] opened 2019-07-09 01:04 UTC
Using Firefox on Android.
Each listed distro information cannot be viewed.

**Comment by Zlopez** [comment] 2019-07-09 07:27
Duplicate of #773 

The new version with fix is already released and there was issue that blocked the deployment, which should be now solved. I will try to deploy this week.

**Closed** 2019-07-09 07:28 UTC
